#!/bin/csh

set PATH=$1;  setenv PATH

setenv LD_LIBRARY_PATH ${2}:$LD_LIBRARY_PATH

#echo command line: ${argv[3-]}

# Pass remaining arguments to gp_gistic_from_seg using ${argv[3-]}
${1}gp_gistic_from_seg ${argv[3-]}

