#!/bin/csh

set PATH=$1;  setenv PATH

setenv LD_LIBRARY_PATH ${2}

#echo command line: ${argv}

# Pass remaining arguments to gp_gistic_from_seg using ${argv[3-]}
${1}gp_gistic_from_seg ${argv[3-]}

