#!/bin/csh

set thisdir = `pwd`

# --- SET UP ENVIRONMENT VARIABLES ---
echo --- setting up environment variables ---
# presumed location of MATLAB Component Runtime (MCR) v7.14
# if the MCR is in a different location, edit the line below
set mcr_root = $thisdir/MATLAB_Component_Runtime
setenv LD_LIBRARY_PATH $mcr_root/v714/runtime/glnxa64:$LD_LIBRARY_PATH
setenv LD_LIBRARY_PATH $mcr_root/v714/sys/os/glnxa64:$LD_LIBRARY_PATH
setenv LD_LIBRARY_PATH $mcr_root/v714/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:$LD_LIBRARY_PATH
setenv LD_LIBRARY_PATH $mcr_root/v714/sys/java/jre/glnxa64/jre/lib/amd64/server:$LD_LIBRARY_PATH
setenv LD_LIBRARY_PATH $mcr_root/v714/sys/java/jre/glnxa64/jre/lib/amd64:$LD_LIBRARY_PATH
setenv XAPPLRESDIR $mcr_root/v714/X11/app-defaults
# (these may be set permanently by copying the above lines into your login script)

# --- RUN GISTIC 2.0 ---
echo --- creating output directory ---
set basedir = $thisdir/example_results/bhill
mkdir -p $basedir 

echo --- running GISTIC ---
set segfile = $thisdir/examplefiles/RTdebugging/1020_1074_1154_1202logR.seg
set markersfile = $thisdir/examplefiles/RTdebugging/Batch1_marker.mk
set refgenefile = $thisdir/refgenefiles/hg18.mat
set alf =
set cnvfile =

./gp_gistic2_from_seg -b $basedir -seg $segfile -mk $markersfile -refgene $refgenefile -alf $alf -cnv $cnvfile -genegistic 0 -smallmem 1 -broad 0 -brlen 0.98 -conf 0.75 -ta 0.1 -td 0.1 -js 4 -qvt 0.25 -rx 1 -v 40
